language: c

dist: bionic

before_install: ci/install-dependencies.sh

script: ci/run-build-and-tests.sh

sudo: required

git:
  depth: 2147483647

env:
  global:
    - VERBOSE=1

matrix:
  include:
    - compiler: gcc
      arch: amd64
      env:
        - TARGET=x86_64
    - compiler: gcc
      arch: arm64-graviton2
      virt: lxd
      group: edge
      env:
        - TARGET=aarch64
    - compiler: gcc-10
      arch: amd64
      env:
        - TARGET=x86_64
    - compiler: gcc-10
      arch: arm64-graviton2
      virt: lxd
      group: edge
      env:
        - TARGET=aarch64
    - compiler: gcc-9
      arch: amd64
      env:
        - TARGET=x86_64
    - compiler: gcc-9
      arch: arm64-graviton2
      virt: lxd
      group: edge
      env:
        - TARGET=aarch64
    - compiler: clang
      arch: amd64
      env:
        - TARGET=x86_64
    - compiler: clang
      arch: arm64-graviton2
      virt: lxd
      group: edge
      env:
        - TARGET=aarch64
